version: '3.8'

services:
  taipit-eai-hub:
    build: .
    container_name: taipit-eai-hub
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - db_data:/app/prisma

volumes:
  db_data:
